---
abstract: 'Creates WSDL documents from (extended) pod'
author:
  - 'Tarek Ahmed <bloerch -at- oelbsk.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-WSDL
requires:
  Carp: 1.03
  IO::Scalar: 2.110
  Pod::Text: 2.21
  Test::More: 0.47
  Test::XML: 0
  XML::Writer: 0.531
  XML::XPath: 1.13
resources:
  repository: http://github.com/tavaresb/Pod--WSDL
version: 0.063
