<?xml version="1.0" encoding="UTF-8"?>
<!-- WSDL for ADSL_Coverage::SOAP::Webservice::HasULLSimple created by Pod::WSDL version: 0.06 on Thu Dec 16 23:21:35 2010 -->
<wsdl:definitions targetNamespace="ADSL_Coverage::SOAP::Webservice::HasULLSimple/ADSL_Coverage/SOAP/Webservice/HasULLSimple" xmlns:impl="ADSL_Coverage::SOAP::Webservice::HasULLSimple/ADSL_Coverage/SOAP/Webservice/HasULLSimple" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns1="ADSL_Coverage::SOAP::Webservice::HasULLSimple/ADSL_Coverage/SOAP/Webservice/HasULLSimple">

	<wsdl:message name="has_ull_coverageRequest">
		<wsdl:part name="dn" type="xsd:string">
			<wsdl:documentation>Numero de telefone</wsdl:documentation>
		</wsdl:part>
		<wsdl:part name="cp" type="xsd:string">
			<wsdl:documentation>Codigo postal 7 digitos ou codigo postal 4 digitos</wsdl:documentation>
		</wsdl:part>
	</wsdl:message>

	<wsdl:message name="has_ull_coverageResponse">
		<wsdl:part name="has_ull_coverageReturn" type="xsd:boolean">
			<wsdl:documentation>Resultado do calculo da elegibilidade</wsdl:documentation>
		</wsdl:part>
	</wsdl:message>

	<wsdl:portType name="ADSL_CoverageSOAPWebserviceHasULLSimpleHandler">
		<wsdl:operation parameterOrder="dn cp" name="has_ull_coverage">
			<wsdl:input message="impl:has_ull_coverageRequest" name="has_ull_coverageRequest" />
			<wsdl:output message="impl:has_ull_coverageResponse" name="has_ull_coverageResponse" />
		</wsdl:operation>

	</wsdl:portType>

	<wsdl:binding name="ADSL_CoverageSOAPWebserviceHasULLSimpleSoapBinding" type="impl:ADSL_CoverageSOAPWebserviceHasULLSimpleHandler">
		<wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="has_ull_coverage">
			<wsdlsoap:operation soapAction="" />
			<wsdl:input name="has_ull_coverageRequest">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="ADSL_Coverage::SOAP::Webservice::HasULLSimple/ADSL_Coverage/SOAP/Webservice/HasULLSimple" use="encoded" />
			</wsdl:input>
			<wsdl:output name="has_ull_coverageResponse">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="ADSL_Coverage::SOAP::Webservice::HasULLSimple/ADSL_Coverage/SOAP/Webservice/HasULLSimple" use="encoded" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>

	<wsdl:service name="ADSL_CoverageSOAPWebserviceHasULLSimpleHandlerService">
		<wsdl:port binding="impl:ADSL_CoverageSOAPWebserviceHasULLSimpleSoapBinding" name="ADSL_CoverageSOAPWebserviceHasULLSimple">
			<wsdlsoap:address location="ADSL_Coverage::SOAP::Webservice::HasULLSimple" />
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>
